version: "3.9"

services:
  backend:
    restart: on-failure
    build: backend
    container_name: backend
    env_file:
      - .env
    depends_on:
      - db
    ports:
      - "8080:8080"

  db:
    image: postgres
    container_name: db
    restart: on-failure
    environment:
      POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_HOST: ${DATABASE_HOST}
    volumes:
      - data-db:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  data-db: