drop table reviews cascade;
drop table orders cascade;
drop table products_stores;
drop table products_tags cascade;
drop table products cascade;
drop table tags cascade;
drop table stores cascade;
drop table couriers cascade;
drop table addresses cascade;
drop table loginForm cascade;
drop table clients cascade;
