drop table order_products;
drop table reviews cascade;
drop table orders cascade;
drop table products_stores;
drop table products cascade;
drop table stores cascade;
drop table administrators cascade;
drop table couriers cascade;
drop table couriers_loginform cascade;
drop table clients_loginform cascade;
drop table clients cascade;
drop table addresses cascade;
