drop table order_products;
drop table orders cascade;
drop table products cascade;
drop table stores_loginform cascade;
drop table stores cascade;
drop table administrators_loginform cascade;
drop table administrators cascade;
drop table administrators_passphrases cascade;
drop table couriers_loginform cascade;
drop table couriers cascade;
drop table clients_loginform cascade;
drop table clients cascade;
drop table addresses cascade;
